soft_dev_assessment/soft_dev_assessment/urls.py
from django.contrib import admin
from django.urls import path
from cars import views

urlpatterns = [  
    path('admin/', admin.site.urls),  
    path('new', views.new),  
    path('show',views.show),  
    path('edit/<int:id>', views.edit),  
    path('update/<int:id>', views.update),  
    path('delete/<int:id>', views.destroy),  
]  

soft_dev_assessment/cars/models.py
from django.db import models

class Car(models.Model):
    name = models.CharField(max_length=100)
    color = models.CharField(max_length=100)
    position = models.IntegerField()

soft_dev_assessment/cars/forms.py
from django import forms  
from cars.models import Car 

class CarForm(forms.ModelForm):  
    class Meta:  
        model = Car  
        exclude = ('position',)

soft_dev_assessment/cars/views.py
from django.shortcuts import render, redirect  
from cars.forms import CarForm  
from cars.models import Car  
# Create your views here.  
def new(request):  
    if request.method == "POST":  
        form = CarForm(request.POST)  
        if form.is_valid():  
            try:  
                form.save()  
                return redirect('/show')  
            except:  
                pass  
    else:  
        form = CarForm()  
    return render(request,'index.html',{'form':form})  
def show(request):  
    cars = Car.objects.all()  
    return render(request,"show.html",{'cars':cars})  
def edit(request, id):  
    car = Car.objects.get(id=id)  
    return render(request,'edit.html', {'car':car})  
def update(request, id):  
    car = Car.objects.get(id=id)  
    form = CarForm(request.POST, instance = car)  
    if form.is_valid():  
        form.save()  
        return redirect("/show")  
    return render(request, 'edit.html', {'car': car})  
def destroy(request, id):  
    car = Car.objects.get(id=id)  
    car.delete()  
    return redirect("/show")  

soft_dev_assessment/cars/templates/edit.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load static %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
<form method="POST" class="post-form" action="/update/{{car.id}}">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Update Details</h3>  
    </div>  
  </div> 
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Car Name:</label>  
    <div class="col-sm-4">  
        <input type="text" name="name" id="id_name" required maxlength="100" value="{{ car.name }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Car Color:</label>  
    <div class="col-sm-4">  
        <input type="text" name="color" id="id_color" required maxlength="254" value="{{ car.color }}" />  
    </div>  
  </div> 
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-success">Update</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>  

soft_dev_assessment/cars/templates/index.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load static %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
<form method="POST" class="post-form" action="/new">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Enter Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Car Id:</label>  
    <div class="col-sm-4">  
      {{ form.id }}  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Car Name:</label>  
    <div class="col-sm-4">  
      {{ form.name }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Car Color:</label>  
    <div class="col-sm-4">  
      {{ form.color }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-primary">Submit</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>  

soft_dev_assessment/cars/templates/show.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Cars</title>  
     {% load static %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
<table class="table table-striped table-bordered table-sm">  
    <thead class="thead-dark">  
    <tr>  
        <th>Car ID</th>  
        <th>Car Name</th>  
        <th>Car Color</th> 
        <th>Actions</th>  
    </tr>  
    </thead>  
    <tbody>  
{% for car in cars %}  
    <tr>  
        <td>{{ car.id }}</td>  
        <td>{{ car.name }}</td>  
        <td>{{ car.color }}</td>   
        <td>  
            <a href="/edit/{{ car.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>  
            <a href="/delete/{{ car.id }}">Delete</a>  
            <a href="/up/{{ car.id }}">Move UP</a>  
            <a href="/down/{{ car.id }}">Move DOWN</a> 
        </td>  
    </tr>  
{% endfor %}  
    </tbody>  
</table>  
<br>  
<br>  
<center><a href="/new" class="btn btn-primary">Add New Car</a></center>  
</body>  
</html>  